### ISSUE TITLE
Illegal Haskell construct encountered

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#316] opened 2018-03-10 19:13 UTC
When I try to promote:
```haskell
$(promoteOnly [d|
    replaceAllGTypes :: (a -> Type -> a) -> [Type] -> [a] -> [a]
    replaceAllGTypes f types as = zipWith f as types
  |])
```
I am greeted with
```haskell
    Illegal Haskell construct encountered:
headed by: DStarT
applied to: []
   |
94 | $(promoteOnly [d|
   |   ^^^^^^^^^^^^^^^...

/Users/LeanderK/Documents/Haskell/Earhart/src/V4/TypeHelpers.hs:94:3: error:
    Q monad failure
   |
94 | $(promoteOnly [d|
   |   ^^^^^^^^^^^^^^^...
Failed, no modules loaded.
```
I don't see anything illegal here? Am I missing something?

EDIT: Same for
```haskell
$(promoteOnly [d|
    toTypes :: [(x, Type)] -> [Type]
    toTypes = map snd
  |])
```

**Comment by RyanGlScott** [comment] 2018-03-10 19:26
Strange, I don't get any such error when I try this:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH

$(promoteOnly [d|
    replaceAllGTypes :: (a -> Type -> a) -> [Type] -> [a] -> [a]
    replaceAllGTypes f types as = zipWith f as types
  |])
```

Can you post the full code you're using?

**Comment by LeanderK** [comment] 2018-03-10 19:37
hmm same error for me when I isolate to `Foo`.
I am using stack with `ghc-8.4.1`
```yaml
resolver: ghc-8.4.1
compiler: ghc-8.4.1
compiler-check: match-exact

extra-deps: 
- eliminators-0.4.1
#because 8.4 is not lts yet
- extra-1.6.4
- singleton-nats-0.4.0.4
- th-abstraction-0.2.6.0
- clock-0.7.2
- singletons-2.4.1
- syb-0.7
- th-desugar-1.8
- th-expand-syns-0.4.4.0
- th-lift-0.7.8
- th-orphans-0.13.5
- th-lift-instances-0.1.11
- th-reify-many-0.1.8
- safe-0.3.17
- vector-0.12.0.1
- primitive-0.6.3.0
```

**Comment by RyanGlScott** [comment] 2018-03-10 19:49
Ah! My mistake, I thought you were referring to `singletons-2.3.1` (which is what your previous bug reports were using). I'll try with `singletons-2.4.1` in a bit.

**Comment by LeanderK** [comment] 2018-03-10 19:51
I just upgraded 😉

**Comment by RyanGlScott** [comment] 2018-03-10 20:15
Ah, I know what is going on here. This happens because of differences in the way Template Haskell reifies `Type` between GHC 8.2 and 8.4.

In GHC 8.2, `Type` is reified like so:

```
> $([t| Type |] >>= stringE . show)
"ConT GHC.Types.Type"
```

But in GHC 8.4, after commit [c948b7865ace38d3d6912db0fc271aa7e9f70d2b](http://git.haskell.org/ghc.git/commit/c948b7865ace38d3d6912db0fc271aa7e9f70d2b), it's now reified as:

```
> $([t| Type |] >>= stringE . show)
"StarT"
```

In `singletons-2.4.1`, we simply don't have a case for `StarT`, which explains the error message you see.

The funny thing is, though, that this might already be fixed in `singletons` HEAD, after commit 862aa5976039ff6e66c82a2f62fbdd89d4af50db, where we changed `th-desugar` to explicitly desugar all uses of `StarT` to `DConT ''Type`. I don't have time to check at the moment, so can you see if you still experience this issue using `singletons` HEAD?

If it has been fixed, one thing you could do to help us is to add a regression test for this behavior in the `singletons` test suite.

**Comment by RyanGlScott** [comment] 2018-03-10 20:16
Also, this works as an ugly workaround on `singletons-2.4.1`:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH
import Data.Typeable (TypeRep)

$(promoteOnly [d|
    replaceAllGTypes :: (a -> TypeRep -> a) -> [TypeRep] -> [a] -> [a]
    replaceAllGTypes f types as = zipWith f as types
  |])
```

**Comment by LeanderK** [comment] 2018-03-10 20:42
I am unable to build it with singletons HEAD because my transitive dependency `singleton-nats` fails to build with it.
```
• Type constructor ‘~>’ cannot be used here
            (Perhaps you intended to use TypeInType)
        • In the second argument of ‘TyFun’, namely ‘((~>) Nat Nat)’
          In the kind ‘TyFun Nat ((~>) Nat Nat)’
```

**Comment by RyanGlScott** [comment] 2018-03-10 21:30
Why do you need to build `singleton-nats` to test this program? It only depends on `singletons`.

**Comment by LeanderK** [comment] 2018-03-10 22:43
I suppose I could have just created a new project that doesn't depend on other libraries. Well, it was a simple fix and I can report that it works using `singletons` HEAD.

>If it has been fixed, one thing you could do to help us is to add a regression test for this behavior in the singletons test suite.

I can do that. Just some examples functions using `Type`?

**Comment by RyanGlScott** [comment] 2018-03-10 22:44
> Just some examples functions using `Type`

**Comment by LeanderK** [comment] 2018-03-10 22:45
sorry, didn't see you reopened it 😉

**Comment by RyanGlScott** [comment] 2018-03-20 18:56
Are you currently working on this, @LeanderK?

**Comment by LeanderK** [comment] 2018-03-20 19:00
I was actually planning to do that, but I have an exam this Thursday which kept me from completing a few tasks (including this) and I am busy with other stuff that came up until Monday.
I try to be at least responsive 😉 You can close it if you want.

**Comment by RyanGlScott** [comment] 2018-03-20 19:03
Thanks. In that case, I'll assign this to myself.

**Closed** 2018-03-20 22:06 UTC
Labels: bug
