### ISSUE TITLE
SingI for symbolic functions?

### ISSUE THREAD

**Issue by Icelandjack** [goldfirere/singletons#272] opened 2017-11-10 04:02 UTC
In deriving I notice code like this (simplified)

```
> pure []; singletons [d| data N = O | S N; increment :: N -> N; increment n = S n |]
    ...
  ======>
    ...
    sIncrement :: Π (n::N) -> Π (Increment n::N)
    sIncrement num = applySing ((singFun1 @SSym0) SS) num
```

where quite a lot of effort is put into constructing a `SSym0` singleton

```haskell
ss :: Sing SSym0
ss = singFun1 @SSym0 SS
```

Would it be {non,}sensical to make an instance (and derive) for `SingI` for each function?

```haskell
instance SingI SSym0 where
  sing :: Sing SSym0
  sing = sungFun1 @SSym0 SS
```

**Comment by RyanGlScott** [comment] 2017-11-10 13:44
Indeed, this is the goal of #252. (I'll close this as a duplicate of that ticket.)

**Closed by RyanGlScott** 2017-11-10 13:44 UTC
