### ISSUE TITLE
Promote to non family type synonym

### ISSUE THREAD

**Issue by brunom** [goldfirere/singletons#253] opened 2017-10-08 00:09 UTC
In
```
data Tree e
    =  Empty
    |  Node e (Tree e) (Tree e)
type Leaf e = 'Node e 'Empty 'Empty
class Foo a
instance Foo (Leaf Int)

$(promote [d|
    data Tree2 e
        =  Empty2
        |  Node2 e (Tree2 e) (Tree2 e)
    leaf2 e = Node2 e Empty2 Empty2
    |])
instance Foo (Leaf2 Int)
```
the second Leaf2 instance won't compile because Leaf2 is a type family synonym and not a plain type synonym. Could this work?

**Comment by RyanGlScott** [comment] 2017-10-08 00:46
> Could this work?

Likely not. At least, not with the way `singletons` is currently designed.

To illustrate the issue more clearly: `leaf2 e = Node2 e Empty2 Empty2` is currently being promoted to a closed type family with one equation:

```haskell
type family Leaf2 e where
      Leaf2 e = Apply (Apply (Apply Node2Sym0 e) Empty2Sym0) Empty2Sym0
```

But you'd rather promote it to a type synonym:

```haskell
type Leaf2 e = Apply (Apply (Apply Node2Sym0 e) Empty2Sym0) Empty2Sym0
```

That would indeed get rid of _one_ type family, but the problem is that there are several other type families lurking underneath in the form of `Apply`! So even after doing all of this work to turn `Leaf2` into a type synonym, you still wouldn't be able to write `instance Foo (Leaf2 Int)` anyways.

**Comment by RyanGlScott** [comment] 2017-10-13 13:29
Another way of putting it: this is really GHC's fault in the end. See the Track tickets [#13773](https://ghc.haskell.org/trac/ghc/ticket/13773) and [#13262](https://ghc.haskell.org/trac/ghc/ticket/13262), which ask for the ability to normalize type family applications like `Apply ...` in instance declarations. (Personally, I think the more satisfying solution would be to wait until these GHC bugs are fixed, rather than redesign `singletons` to work around them.)

**Comment by RyanGlScott** [comment] 2018-02-18 23:56
Closing, as there is nothing that we can do on the `singletons` end to work around this (except for a complete rewrite of the library, which isn't realistic).

**Closed by RyanGlScott** 2018-02-18 23:56 UTC
Labels: Blocked upstream, bug
