### ISSUE TITLE
having trouble getting singletons-th to work  on ghc 9.2

### ISSUE THREAD

**Issue by cartazio** [goldfirere/singletons#555] opened 2023-02-22 23:13 UTC
heres enough to show the problem (nb: i'm using language mode GHC 2021)

```haskell
{-# Language DataKinds,TypeFamilies, GADTs, OverloadedLabels #-}
{-# Language TemplateHaskell, QuasiQuotes #-} 
{-# LANGUAGE NoNamedWildCards #-}
module Totall.Secret.Exp  where 

import Data.Kind (Type)
import Data.Word (Word64)
import Data.Int(Int64)
import Data.Singletons.TH 
import Prelude.Singletons
-- source types, by no means complete, 
{-

-}

$( singletons[d|
data MyPropKind = Location   
                | Quaternion 
             
    deriving(Eq,Ord,Show)                
|]
```
the error i see is pretty bad parser error message, 
but to make matter worse, it seems like its really an issue with quasi quotes themselves... 

anyways, after I got that working, i've encountered a new problem! 

```haskell
    error:
    Cannot find type annotation for ==
   |
18 | $(singletons [d| data MyPropKind = 
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

this one really has my head scratching... whats going on here?

**Comment by cartazio** [comment] 2023-02-22 23:49
seems to be possibly https://github.com/goldfirere/singletons/issues/536#issuecomment-1229174146 

i'll see if that fixes it... do i just need to have singletons-prelude or whatever in scope for that to work?

**Comment by RyanGlScott** [comment] 2023-02-23 12:24
The parsing issue is caused by (1) the `$(singletons ...` bit lacking a closing parenthesis, and (2) the lack of indentation. Here is a version that does parse:

```hs
$(singletons [d|
  data MyPropKind = Location
                  | Quaternion

      deriving(Eq,Ord,Show)
  |])
```

After that change, I don't get quite the same error message that you do, but I do get a similar error:

```
[1 of 1] Compiling Totall.Secret.Exp ( Foo.hs, interpreted )

Foo.hs:16:2: error:
    Not in scope: type constructor or class ‘ThenCmpSym0’
   |
16 | $(singletons [d|
   |  ^^^^^^^^^^^^^^^...

Foo.hs:16:2: error:
    Not in scope: type constructor or class ‘ThenCmpSym0’
   |
16 | $(singletons [d|
   |  ^^^^^^^^^^^^^^^...

Foo.hs:16:2: error:
    Not in scope: type constructor or class ‘ThenCmpSym0’
   |
16 | $(singletons [d|
   |  ^^^^^^^^^^^^^^^...

Foo.hs:16:2: error:
    Not in scope: type constructor or class ‘ThenCmpSym0’
   |
16 | $(singletons [d|
   |  ^^^^^^^^^^^^^^^...
```

The reason this happens is because `ThenCmpSym0` (a type-level counterpart to the `thenCmp` function) hasn't been imported. `Prelude.Singletons` only re-exports promoted/singled versions of functions from the `Prelude`, and `thenCmp` isn't one of them. The [`thenCmp` function](https://github.com/goldfirere/singletons/blob/a169d3f6c0c8e962ea2983f60ed74e507bca9b2b/singletons-base/src/Data/Ord/Singletons.hs#L93-L96) is in `singletons-th`'s implementation of derived `Ord` instances, and it must be imported explicitly. Two possible ways to fix your program are to import one of the following:

1. `Data.Ord.Singletons` (which defines `thenCmp` and friends)
2. `Data.Singletons.Base.TH`, which re-exports `Data.Singletons.TH` alongside definitions needed to make derived instances work

If I import one of those module and enable `UndecidableInstances`, then your example works.

-----

While the solution above should work, I've realized (after writing this up) that we really don't need to define a separate `thenCmp` function at all. `thenCmp`:

https://github.com/goldfirere/singletons/blob/a169d3f6c0c8e962ea2983f60ed74e507bca9b2b/singletons-base/src/Data/Ord/Singletons.hs#L93-L96

Is just `(<>)` in the `Semigroup Ordering` instance. We could make `singletons-th` generate uses of `(<>)` instead of `thenCmp` in derived `Ord` instances, which would mean that your example would Just Work™ out of the box. (In general, I don't think we could guarantee this for all possible derived instances, but this would be one less papercut to deal with.)

**Closed** 2023-02-25 12:17 UTC
