### ISSUE TITLE
GHC 8.6.1: failure to build with latest `th-desugar`

### ISSUE THREAD

**Issue by deepfire** [goldfirere/singletons#369] opened 2018-10-30 02:08 UTC
Again, as in https://github.com/goldfirere/th-desugar/issues/96, not `singletons`' failure but:
```
[ 4 of 68] Compiling Data.Singletons.Syntax ( src/Data/Singletons/Syntax.hs, dist/build/Data/Singletons/Syntax.o )

<no location info>: error:
    Failed to load interface for ‘Language.Haskell.TH.Desugar.AST’
There are files missing in the ‘th-desugar-1.8’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
[ 5 of 68] Compiling Data.Singletons.Util ( src/Data/Singletons/Util.hs, dist/build/Data/Singletons/Util.o )
/nix/store/5r68n8h7mz3z9623jqngqg3vj041c141-th-desugar-1.8/lib/ghc-8.6.1/x86_64-linux-ghc-8.6.1/th-desugar-1.8-GogzLGV4txJHGzPgbKc3X/Language/Haskell/TH/Desugar.hi
Declaration for $fDesugar[][]0:
  Can't find interface-file declaration for type constructor or class DCxt
    Probable cause: bug in .hi-boot file, or inconsistent .hi file
    Use -ddump-if-trace to get an idea of which file caused the error

<no location info>: error:
    Cannot continue after interface file error
builder for '/nix/store/52yn77rd1vr03vc4vlcipzgdfrk6pi2n-singletons-2.4.1.drv' failed with exit code 1
error: build of '/nix/store/52yn77rd1vr03vc4vlcipzgdfrk6pi2n-singletons-2.4.1.drv' failed
```
..whereas `DCxt` is neither a type constructor, nor a class -- it's a type alias:
```
$ ag DCxt /nix/store/kifmcfczjwfvpk22gb1bzw790mc2yw3k-source
/nix/store/kifmcfczjwfvpk22gb1bzw790mc2yw3k-source/Language/Haskell/TH/Desugar/AST.hs
43:data DType = DForallT [DTyVarBndr] DCxt DType
57:type DCxt = [DPred]
60:data DPred = DForallPr [DTyVarBndr] DCxt DPred
96:          | DDataD NewOrData DCxt Name [DTyVarBndr] (Maybe DKind) [DCon] [DDerivClause]
98:          | DClassD DCxt Name [DTyVarBndr] [FunDep] [DDec]
99:          | DInstanceD (Maybe Overlap) DCxt DType [DDec]
104:          | DDataInstD NewOrData DCxt Name [DType] (Maybe DKind) [DCon] [DDerivClause]
107:          | DStandaloneDerivD (Maybe DDerivStrategy) DCxt DType
167:data DCon = DCon [DTyVarBndr] DCxt Name DConFields
297:data DDerivClause = DDerivClause (Maybe DDerivStrategy) DCxt

/nix/store/kifmcfczjwfvpk22gb1bzw790mc2yw3k-source/Language/Haskell/TH/Desugar/Core.hs
887:       => Con -> q [(Name, [DTyVarBndr], DCxt, DConFields, Maybe DType)]
1054:dsCxt :: DsMonad q => Cxt -> q DCxt
1090:dsPred :: DsMonad q => Pred -> q DCxt

/nix/store/kifmcfczjwfvpk22gb1bzw790mc2yw3k-source/Language/Haskell/TH/Desugar.hs
26:  DExp(..), DLetDec(..), DPat(..), DType(..), DKind, DCxt, DPred(..),
134:instance Desugar Cxt DCxt where

/nix/store/kifmcfczjwfvpk22gb1bzw790mc2yw3k-source/Language/Haskell/TH/Desugar/Sweeten.hs
348:cxtToTH :: DCxt -> Cxt
```
Revisions:
```
$ cat pkgs/def/github/th-desugar.rev
1d164b669079fe57181af95bbbe4749dbf08ab78

$ cat pkgs/def/github/singletons.rev
f535872b292a14a74a710ce05bcc782269a76793
```

**Comment by RyanGlScott** [comment] 2018-10-31 13:48
I strongly suspect that this is more fallout from the strange setup used in goldfirere/th-desugar#96. The cause of that bug has been identified, so I'm going to optimistically close this under the assumption that fixing goldfirere/th-desugar#96 also fixes this bug. Please re-open if you still experience this.

**Closed by RyanGlScott** 2018-10-31 13:48 UTC
