### ISSUE TITLE
Wildcard doesn't work

### ISSUE THREAD

**Issue by Icelandjack** [goldfirere/singletons#246] opened 2017-08-22 06:06 UTC
```haskell
import Data.Singletons.TH

singletons [d|
  data Nat = O | S Nat

  eqNat :: Nat -> Nat -> Bool
  eqNat O     O     = True
  eqNat (S n) (S m) = eqNat n m
  eqNat _     _     = False
  |]
```

gives

```
<- /tmp/azzuh.hs:(3,1)-(11,4): error:
       • Couldn't match type ‘EqNat t t1’ with ‘'False’
         Expected type: Sing (Apply (Apply EqNatSym0 t) t1)
           Actual type: Sing 'False
       • In the expression: SFalse
         In an equation for ‘sEqNat’: sEqNat _ _ = SFalse
       • Relevant bindings include
           sEqNat :: Sing t -> Sing t1 -> Sing (Apply (Apply EqNatSym0 t) t1)
             (bound at /tmp/azzuh.hs:3:1)
     |
   3 | singletons [d|
     | ^^^^^^^^^^^^^^...
   Failed, modules loaded: none.
```

I have to list all the cases

```haskell
singletons [d|
  data Nat = O | S Nat

  eqNat :: Nat -> Nat -> Bool
  eqNat O     O     = True
  eqNat (S n) (S m) = eqNat n m
  eqNat (S _) O     = False
  eqNat O     (S _) = False
  |]
```

**Comment by vagarenko** [comment] 2017-08-22 08:40
Isn't it duplicate of #245?

**Comment by RyanGlScott** [comment] 2017-08-22 13:03
Indeed. As noted in the `README`, `singletons` has trouble with definitions that use overlapping patterns. The workaround is to just enumerate all of the overlapped patterns, as you did above.

It's worth noting that at one point, there was an experimental feature called "match flattening" which would attempt to automatically enumerate overlapping patterns during singling. But this ended up blowing up compilation times significantly, so this design wasn't pursued further.

**Closed by RyanGlScott** 2017-08-22 13:03 UTC

**Comment by goldfirere** [comment] 2017-08-22 15:38
To be fair, the blowup due to match flattening was never fully explored. It's possible that the problem has a solution, but no one ever took the time to really model where the blowup is. For example, we don't know whether its singletons' running time, the size of the produced code, GHC's running time, or some contributions from all of these. Perhaps there's even a solid GHC performance bug to be found. So there's no reason to give up on match-flattening if someone wants to work the problem.
