### ISSUE TITLE
Symbol in datatypes

### ISSUE THREAD

**Issue by sweirich** [goldfirere/singletons#177] opened 2017-01-11 16:27 UTC
$(singletons [d|
  -- Note: Ord automatically defines "max"
  data Occ = Str | Opt | Many deriving (Eq, Ord, Show)
  data Pair = Symbol :=> Occ
  |])

produces the error message:

*RegexpOcc Data.List> :load "RegexpOcc.hs"
[1 of 1] Compiling RegexpOcc        ( RegexpOcc.hs, interpreted )

RegexpOcc.hs:47:3: warning: [-Wdeferred-type-errors]
    • Couldn't match type ‘Data.Text.Internal.Text’ with ‘Symbol’
      Expected type: Symbol
        Actual type: Demote Symbol
    • In the first argument of ‘P’, namely ‘fromSing b_afOOC’
      In the expression: P (fromSing b_afOOC) (fromSing b_afOOD)
      In an equation for ‘fromSing’:
          fromSing (SP b_afOOC b_afOOD)
            = P (fromSing b_afOOC) (fromSing b_afOOD)

RegexpOcc.hs:47:3: warning: [-Wdeferred-type-errors]
    • Couldn't match type ‘Symbol’ with ‘Data.Text.Internal.Text’
      Expected type: Demote Symbol
        Actual type: Symbol
    • In the first argument of ‘toSing’, namely ‘b_afOOE’
      In the first argument of ‘(,)’, namely
        ‘toSing b_afOOE :: SomeSing Symbol’
      In the expression:
        (,)
          (toSing b_afOOE :: SomeSing Symbol)
          (toSing b_afOOF :: SomeSing Occ)
Ok, modules loaded: RegexpOcc.

**Comment by goldfirere** [comment] 2017-01-11 16:45
Duplicate of #82. Yes, this would be nice, but it's not trivial to implement.

**Closed by goldfirere** 2017-01-11 16:45 UTC

**Comment by sweirich** [comment] 2017-01-11 16:50
Is it possible to do by hand for use in other promoted code?

I know what to do for :%=>, but what is the right definition of :=>$ ?

**Comment by goldfirere** [comment] 2017-01-11 16:58
```
$(singletons [d|
-- Note: Ord automatically defines "max"
data Occ = Str | Opt | Many deriving (Eq, Ord, Show)
data Pair' symbol = symbol :=> Occ
|])

type Pair = Pair' Symbol
```

Something tells me it can't be that easy, but I somehow don't see where that goes wrong.
