### ISSUE TITLE
Can we write functions with codomain `Type` using promotion?

### ISSUE THREAD

**Issue by ocharles** [goldfirere/singletons#144] opened 2016-05-03 11:09 UTC
I'd like to be able to write the following:

``` haskell
$(promote [d|
  data BaseType = INT | TEXT

  haskellType :: BaseType -> Type
  haskellType INT = Int
  haskellType TEXT = String
  |])
```

can `singletons` deal with that, perhaps in GHC 8? I haven't been able to try, as I don't think `singletons` compiles with GHC 8 at the moment.

**Comment by andrewthad** [comment] 2016-05-11 18:31
You could always write `HaskellType` as a type family and then use:

    genDefunSymbols [''HaskellType]

to get `HaskellTypeSym0`, etc. Since the value-level `haskellType` cannot be kept, and the singletonized `sHaskellType` is not possible either (because there cannot be a `Sing Type` data instance), I don't see what can be gained from writing it in the splice like you want to. Is it just for syntactic convenience, or it there another reason?

**Comment by goldfirere** [comment] 2016-05-11 18:35
No, this isn't possible. (Though compiling and using the version of `singletons` here on github should work with GHC 8.) The problem is one of namespaces: GHC expects term-level capitalized things to live in the data constructor namespace, and `Int` and `String` do not. I suppose `singletons` could be taught to look in a different namespace than GHC, now that TH supports the use of unbound identifiers in quotes. Is that worth it? Perhaps.

**Comment by ocharles** [comment] 2016-05-12 08:21
It is for the most part syntactic, yes. Sorry for not adding my motivation to the issue. Essentially I am writing a library with some basic functionality, but it would be fairly typical for my users to extend/replace the universe of types within my library with something richer. I'd rather have them write familiar Haskell within some funny TH markers, than have them learn how to write type class instances. A fairly superficial reason, perhaps, but it would make things easier. Generally Haskell has way too much syntax for all of this type magic, and `singletons` is something of a cure there.

**Comment by goldfirere** [comment] 2016-12-09 04:06
Looking back at this ticket, I think this would not be hard -- but it doesn't need to be `singletons` that does the light lifting. All you need is a `preferTypeNameSpace :: Data a => a -> Q a` that:

1. Finds all uppercase `Name`s and tries to look them up in the type namespace; and
2. Looks for unbound names in expressions (`UnboundVarE`) and (if the name conversion is successful) changes them to `VarE`.

That should do it. Then just use `promote <=< preferTypeNameSpace` and you should be golden.

I'm afraid I'm not quite inspired to write/test/maintain this functionality, but I don't think it would be hard for you to make a function/small package to do this.

I'm going to close this ticket, having "solved" the ticket by clever delegation. Do reopen if you feel I've mischaracterized the problem or need further advice in implementing `preferTypeNameSpace` -- I am happy to help, just not to take the lead right now.

**Closed by goldfirere** 2016-12-09 04:06 UTC
